import requests
from md_to_html import convert
# 1. Recuperer le dataset depuis Overpass API
def get_dataset():
    """
    Récupère tous les parcs dans une zone géographique donnée.
    """
    url = "https://overpass.kumi.systems/api/interpreter"

    query = """
    /*
    This has been generated by the overpass-turbo wizard.
    The original search was:
    “park in sfax”
    */
    [out:json][timeout:25];
    // fetch area “sfax” to search in
    area(id:3601434957)->.searchArea;
    // gather results
    nwr["leisure"="park"](area.searchArea);
    // print results
    out geom;
    """
    # Envoyer la requête à l'API Overpass
    response = requests.post(
        url,
        data=query,
        headers={"User-Agent": "Mozilla/5.0"}
    )

    if response.status_code != 200:
        raise Exception("Erreur Overpass API")

    return response.json()

# 2. calculer des statistiques
def compute_statistics(data):
    """
    Calcule des statistiques simples sur les parcs.
    """
    elements = data.get("elements", [])

    total = len(elements)
    with_name = 0
    without_name = 0

    for element in elements:
        tags = element.get("tags", {})
        if "name" in tags:
            with_name += 1
        else:
            without_name += 1

    return total, with_name, without_name

# 4. Générer une fiche Markdown
def dataset_to_md(data, stats, filename):
    """
    Génère une fiche Markdown avec la liste des parcs et les statistiques.
    """
    elements = data.get("elements", [])
    total, with_name, without_name = stats

    with open(filename, "w", encoding="utf-8") as f:
        f.write("# Parcs dans la zone étudiée\n\n")

        f.write("## Statistiques\n")
        f.write(f"- Nombre total de parcs : {total}\n")
        f.write(f"- Parcs avec nom : {with_name}\n")
        f.write(f"- Parcs sans nom : {without_name}\n\n")

        f.write("## Liste des parcs\n")
        for element in elements:
            tags = element.get("tags", {})
            name = tags.get("name", "Parc sans nom")
            f.write(f"- {name}\n")

# 5. Fonction principale
def infos_locales():
    """
    Fonction principale : récupération → statistiques → Markdown → HTML.
    """
    data = get_dataset()
    stats = compute_statistics(data)

    md_file = "../markdown/infos_locales.md"
    html_file = "../html/infos_locales.html"

    dataset_to_md(data, stats, md_file)
    convert(md_file, html_file)

    print("Fiche infos_locales générée avec succès.")

# 6. Exécution du script
if __name__ == "__main__":
    infos_locales()
